export const MessageConstants = {
  INTERNAL_SERVER_ERROR: "Internal server error",
  BAD_REQUEST: "Invalid request data",
  POLICY_UPDATED:"Policy Updated successfully",
  POLICY_FETCHED:"Policy fetched successfully",
  ATTENDENCE_MARKED:"Attendence marked successfully",
  ATTENDENCE_DETAILS_FETCHED:"Attendence details fetched successfully",
  ATTENDENCE_EDITED:"Attendence edited successfully",
  EMPLOYEE_ADDED:"Employee added successfully",
  EMPLOYEE_UPDATED:"employee updated",
  INVITATION_SENDED:"Invitation sended successfully" ,
  PASSWORD_SET_UP:"Password set-up successfully" ,
  NOT_FOUND:"Not found",
  EMPLOYEE_TERMINATED:"Employee terminated successfully",
  POSITION_ADDED:"Position added successfully" ,
  POSITION_FETCHED:"Positions fetched sucessfully..",
  EMPLOYEES_FETCHED:"Employees fetched succesfuly",
  EMPLOYEES_COUNT_FETCHED:"Employees count fetched successfully",
  LEAVE_APPLIED:"Leave applied successfully",
  FETCH_APPLIED_LEAVE:"Fetched Applied leaves",
  LEAVE_MANAGED:"Leave Managed successfully..",
  FETCH_REMAINING_LEAVE:"Remaining leaves fetched sucessfully",
  LEAVE_EDITED:"Leave edited successfully"
};
