apiVersion: v1
data:
  JWT_SECRET: bW9pZGVlbnNoYWNwMjAwNGp3dA==
  MONGO_URI: bW9uZ29kYitzcnY6Ly9mYXJsaW5rOnJYVVBwT3A1WEMzY0ZwMDRAbWVybi51ajNjZy5tb25nb2RiLm5ldC9mYXJsaW5rLWNoYXQtbWVldGluZz9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHkmYXBwTmFtZT1tZXJu
  REFRESH_SECRET: bW9pZGVlbg==
kind: Secret
metadata:
  creationTimestamp: "2025-02-17T06:32:27Z"
  name: chat-meeting-service-secrets
  namespace: default
  resourceVersion: "32718"
  uid: 16064e95-94f2-4c10-a82d-69b2236f4c4a
type: Opaque
