apiVersion: v1
data:
  EMAIL_PASS: bGR6aSBwdW54IHh2cXcgZmdneA==
  EMAIL_SECRET: bW9pZGVlbnNoYWNwMjAwNGVtYWls
  EMAIL_USER: ZmFybGluazQ0M0BnbWFpbC5jb20=
  JWT_SECRET: bW9pZGVlbnNoYWNwMjAwNGp3dA==
  MONGO_URI: bW9uZ29kYitzcnY6Ly9mYXJsaW5rOnJYVVBwT3A1WEMzY0ZwMDRAbWVybi51ajNjZy5tb25nb2RiLm5ldC9mYXJsaW5rLXByb2plY3Q/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9bWVybg==
  REFRESH_SECRET: bW9pZGVlbnNoYWNwMjAwNHJlZnJlc2hqd3Q=
kind: Secret
metadata:
  creationTimestamp: "2025-02-17T06:28:08Z"
  name: project-service-secrets
  namespace: default
  resourceVersion: "29888"
  uid: bf113d3a-1721-44da-8c45-d6d1c7e6e018
type: Opaque
