apiVersion: v1
data:
  PORT: "3001"
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: "5672"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"PORT":"3001","RABBITMQ_HOST":"rabbitmq","RABBITMQ_PORT":"5672"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":null,"name":"user-service-config","namespace":"default"}}
  creationTimestamp: "2025-02-17T06:37:32Z"
  name: user-service-config
  namespace: default
  resourceVersion: "36036"
  uid: 8cc8a055-b197-41c7-bf87-81634d4950b5
