apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: "2025-02-17T06:27:01Z"
  name: user-service-secrets
  namespace: default
  resourceVersion: "29168"
  uid: 2a0a6552-a3ba-4f91-9576-979143d03f5d
type: Opaque
